name: Python Telegram Bot

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  run_bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version if different

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure python-telegram-bot and paramiko are listed in requirements.txt

    - name: Run bot script
      env:
        TOKEN: ${{ secrets.TOKEN }}  # Ensure TOKEN is set as a secret in your GitHub repository
      run: |
        python main.py
